name: ProgChem
channels:
        - conda-forge
dependencies:
        - numpy==1.18.5
        - scipy
        - sympy
        - pandas
        - scikit-learn
        - seaborn
        - matplotlib
        - rdkit
        - deepchem
        - tensorflow
        - scikit-learn
        - joblib
